services:
  - type: web
    name: coding-winner-bot
    env: docker
    dockerfilePath: ./Dockerfile
    region: singapore
    plan: free
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: DISCORD_APPLICATION_ID
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: coding-winner-db
          property: connectionString
      - key: TZ
        value: Asia/Tokyo

databases:
  - name: coding-winner-db
    databaseName: coding_winner
    user: coding_winner
    region: singapore
    plan: free
